import { FlowBackground, HeroBackground } from "@/components/marketing/HeroBackground";
import { AiVisual } from "@/components/marketing/AiVisual";
import { Reveal } from "@/components/marketing/Reveal";
import { StorySlider } from "@/components/marketing/StorySlider";
import { Button } from "@/components/ui/Button";
import { ArrowDown, ArrowRight, ArrowUpRight, Bot, ChartNoAxesCombined, Check, CircleCheck, Clock3, FileCheck2, FileText, MessageSquareText, ShieldCheck, Sparkles, Zap } from "lucide-react";
import Link from "next/link";

const steps = [
  { number: "01", title: "Bring your invoices together", body: "Create or import customers and invoices. Every amount, due date, and payment link stays tied to a real record.", icon: FileText },
  { number: "02", title: "Set the rules once", body: "Choose your reminder tone, timing, quiet hours, approval mode, and escalation contact before activating the collector.", icon: Bot },
  { number: "03", title: "Focus on the exceptions", body: "Replies become clear actions. Promises, disputes, payment claims, and uncertain messages surface for your team.", icon: MessageSquareText },
  { number: "04", title: "Close the loop with confidence", body: "Verified payment stops follow-up. The full invoice timeline remains visible for every decision.", icon: CircleCheck },
];

const capabilities = [
  { icon: FileCheck2, title: "Invoicing, without the sprawl", body: "Draft, import, track, and organize every invoice in one calm workspace.", href: "/features#invoice-management" },
  { icon: Sparkles, title: "Thoughtful AI reminders", body: "Messages use approved invoice facts and your chosen tone, timing, and rules.", href: "/features#ai-reminders" },
  { icon: MessageSquareText, title: "Every reply has a place", body: "See the conversation, classification, owner, and next action together.", href: "/features#conversation-history" },
  { icon: ChartNoAxesCombined, title: "A clearer picture of cash", body: "Aging, collection activity, and payment trends at a glance.", href: "/features#reporting" },
];

const faqs = [
  { q: "Can AI mark an invoice as paid?", a: "No. A payment is recorded only after authorized manual entry or a verified payment event. A customer's email claim pauses collection for review." },
  { q: "Can our team approve reminders first?", a: "Yes. Choose approval for the first message, every message, or firm-stage messages. You can also pause a customer or invoice." },
  { q: "What happens when a customer disputes an invoice?", a: "Automated collection pauses and the thread moves into your review queue with the reason, history, and suggested next action." },
  { q: "Can we start with existing invoices?", a: "Yes. The workspace includes CSV import with field mapping and a validation preview, plus manual entry for individual records." },
];

function InvoiceScene() {
  return <div className="relative mx-auto w-full max-w-[570px]" aria-label="Illustrative preview of the Receivly workspace">
    <div className="absolute -inset-4 rounded-[3rem] bg-[radial-gradient(ellipse,#11118446,transparent_68%)] blur-3xl" />
    <div className="relative overflow-hidden rounded-[1.4rem] border border-white/20 bg-[#101427]/95 shadow-[0_35px_100px_rgba(0,0,0,.45)] backdrop-blur-xl">
      <div className="flex h-10 items-center justify-between border-b border-white/10 px-4"><div className="flex gap-1.5"><i className="h-2 w-2 rounded-full bg-[#ff7c83]" /><i className="h-2 w-2 rounded-full bg-[#ffd379]" /><i className="h-2 w-2 rounded-full bg-[#7ee1b8]" /></div><span className="text-[10px] font-medium tracking-[.12em] text-white/55">RECEIVLY / WORKSPACE</span><span className="h-2 w-2 rounded-full bg-emerald-400 shadow-[0_0_12px_#34d399]" /></div>
      <div className="grid grid-cols-[55px_1fr] sm:grid-cols-[120px_1fr]">
        <div className="border-r border-white/10 bg-white/[0.02] px-2 py-4 sm:px-3"><div className="mb-5 flex items-center justify-center gap-2 sm:justify-start"><span className="grid h-6 w-6 place-items-center rounded-md bg-fuchsia-500 text-xs font-bold text-white">R</span><span className="hidden text-xs font-semibold text-white sm:inline">receivly</span></div>{["Overview", "Invoices", "Conversations", "AI Collector", "Reports"].map((item, i) => <div key={item} className={`mb-1.5 flex h-7 items-center gap-2 rounded-lg px-1.5 text-[10px] ${i === 0 ? "bg-violet-500/20 text-white" : "text-white/50"}`}><span className="h-2.5 w-2.5 rounded-[3px] border border-current" /><span className="hidden sm:inline">{item}</span></div>)}</div>
        <div className="min-w-0 p-3 sm:p-5"><div className="flex items-start justify-between gap-2"><div><p className="text-[10px] uppercase tracking-[.12em] text-white/45">Your workspace</p><p className="mt-1 text-base font-semibold text-white sm:text-lg">Good morning, Alex</p></div><span className="hidden rounded-full border border-emerald-400/20 bg-emerald-400/10 px-2 py-1 text-[10px] text-emerald-200 sm:block">● Collector active</span></div>
          <div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-3"><div className="rounded-xl border border-white/10 bg-white/[0.05] p-2.5"><p className="text-[10px] text-white/55">Outstanding</p><p className="mt-1 text-base font-semibold text-white">$128,450</p><p className="text-[10px] text-emerald-300">↗ 8.2% collected</p></div><div className="rounded-xl border border-white/10 bg-white/[0.05] p-2.5"><p className="text-[10px] text-white/55">Overdue</p><p className="mt-1 text-base font-semibold text-white">$32,710</p><p className="text-[10px] text-amber-300">12 invoices</p></div><div className="hidden rounded-xl border border-white/10 bg-white/[0.05] p-2.5 sm:block"><p className="text-[10px] text-white/55">Promised</p><p className="mt-1 text-base font-semibold text-white">$18,200</p><p className="text-[10px] text-sky-300">4 payments due</p></div></div>
          <div className="mt-2 rounded-xl border border-white/10 bg-white/[0.035] p-3"><div className="flex items-center justify-between"><p className="text-[11px] font-semibold text-white">Collection flow</p><p className="text-[10px] text-white/45">Last 30 days</p></div><div className="mt-3 flex h-16 items-end justify-between gap-1.5">{[28, 41, 34, 57, 50, 64, 48, 69, 61, 78, 74, 92, 84, 96, 88, 100].map((h, i) => <span key={i} className="min-w-0 flex-1 rounded-t-[3px] bg-gradient-to-t from-blue-600/70 to-fuchsia-400/90" style={{ height: `${h}%` }} />)}</div></div>
          <div className="mt-2 flex items-center gap-2 rounded-xl border border-fuchsia-300/15 bg-fuchsia-400/[0.07] p-2.5"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-fuchsia-500/20 text-fuchsia-200"><Sparkles size={14} /></span><div className="min-w-0"><p className="text-[11px] font-medium text-white">3 conversations need review</p><p className="text-[10px] text-white/50">Dispute · Payment claim · Promise</p></div></div>
        </div>
      </div>
    </div>
    <div className="absolute -bottom-5 -left-3 hidden items-center gap-2 rounded-xl border border-white/20 bg-[#20213b]/95 px-3 py-2.5 shadow-2xl backdrop-blur-md sm:flex"><Check size={15} className="text-emerald-300" /><div><p className="text-[11px] font-semibold text-white">Payment verified</p><p className="text-[10px] text-white/50">Collection stopped</p></div></div>
  </div>;
}

function Marquee() {
  const words = <><span>Clarity in every invoice</span><span>Thoughtful follow-up</span><span>People in control</span><span>Momentum you can see</span></>;
  return <div className="landing-marquee" aria-label="Clarity in every invoice. Thoughtful follow-up. People in control. Momentum you can see."><div className="landing-marquee-track"><div className="landing-marquee-group" aria-hidden="true">{words}</div><div className="landing-marquee-group" aria-hidden="true">{words}</div></div></div>;
}

export default function HomePage() {
  return <div className="landing-page">
    <section className="hero-dark relative flex min-h-[710px] items-center justify-center overflow-hidden bg-[#070914] text-white sm:min-h-[760px] lg:min-h-[min(860px,100svh)]">
      <HeroBackground />
      <div className="relative z-10 mx-auto w-full max-w-[1050px] px-5 pb-20 pt-32 text-center sm:px-8 lg:pt-24">
        <Reveal><p className="text-[11px] font-semibold uppercase tracking-[.28em] text-white/80 sm:text-xs">A more considered way to collect</p>
          <h1 className="mx-auto mt-7 max-w-[990px] text-[clamp(4.5rem,11vw,10.5rem)] leading-[.76] text-white">Get paid.<br /><span className="script-accent relative top-1 text-[.96em] sm:top-2">Stay human.</span></h1>
          <p className="mx-auto mt-10 max-w-[620px] text-[14px] leading-relaxed text-white/85 sm:text-base">One beautiful workspace for invoices, thoughtful AI follow-up, and the conversations that need a human touch.</p>
          <div className="mt-7 flex flex-wrap justify-center gap-3"><Link href="/signup"><Button size="lg">Get started <ArrowUpRight size={17} /></Button></Link><Link href="/features"><Button size="lg" variant="outline" className="border-white/50 bg-white/[.07] text-white hover:bg-white/15">Explore the platform <ArrowRight size={17} /></Button></Link></div>
        </Reveal>
      </div>
      <a href="#discover" aria-label="Scroll to discover Receivly" className="absolute bottom-6 left-1/2 z-10 flex -translate-x-1/2 flex-col items-center gap-2 text-[10px] font-semibold uppercase tracking-[.2em] text-white/70">Scroll to discover <ArrowDown size={17} /></a>
    </section>
    <Marquee />

    <section id="discover" className="relative overflow-hidden border-b border-foreground/10 py-20 sm:py-28"><div className="mx-auto max-w-[1260px] px-4 sm:px-7">
      <Reveal><p className="section-kicker">Built for the real work</p><div className="mt-4 grid gap-6 lg:grid-cols-[1.15fr_.85fr] lg:items-end"><h2 className="max-w-[750px] text-[clamp(3.4rem,6vw,5.8rem)] leading-[.92]">From overdue to <span className="script-accent whitespace-nowrap">under control.</span></h2><p className="max-w-md text-[14px] leading-relaxed text-foreground/65 sm:text-base">Receivly keeps the moving parts of collection connected, so finance teams spend less time chasing and more time resolving.</p></div></Reveal>
      <div className="mt-11 grid gap-3 md:grid-cols-3">{[{ icon: Clock3, title: "Time back", body: "Routine follow-up moves with your rules." }, { icon: ShieldCheck, title: "Control intact", body: "Sensitive decisions stay with your team." }, { icon: Zap, title: "Momentum visible", body: "Every action, reply, and payment has context." }].map(({ icon: Icon, title, body }, i) => <Reveal key={title} delay={i * .07}><div className="glass-panel h-full rounded-2xl p-6"><Icon size={22} className="text-[#e4459a]" /><h3 className="mt-6 text-xl font-semibold">{title}</h3><p className="mt-2 text-[13px] leading-relaxed text-foreground/65">{body}</p></div></Reveal>)}</div>
    </div></section>

    <section className="relative overflow-hidden border-b border-foreground/10 py-20 sm:py-28"><FlowBackground /><div className="relative z-10 mx-auto max-w-[1260px] px-4 sm:px-7"><Reveal><p className="section-kicker">The work, made visible</p><div className="mt-3 flex flex-col justify-between gap-4 md:flex-row md:items-end"><h2 className="max-w-[710px] text-[clamp(3.3rem,5.5vw,5.6rem)] leading-[.92]">A calmer path from <span className="script-accent">sent to settled.</span></h2><p className="max-w-[350px] text-[13px] leading-relaxed text-foreground/65 sm:text-sm">Move through the collection journey with complete context at every turn.</p></div></Reveal><StorySlider /></div></section>

    <section className="flow-section relative overflow-hidden border-b border-foreground/10 py-20 sm:py-28"><div className="flow-stroke pointer-events-none absolute left-1/2 top-1/2 h-[78%] w-[78%] -translate-x-1/2 -translate-y-1/2 rounded-[45%] opacity-30" /><div className="relative mx-auto grid max-w-[1260px] gap-12 px-4 sm:px-7 lg:grid-cols-[.95fr_1.05fr] lg:gap-16">
      <div className="lg:sticky lg:top-28 lg:self-start"><Reveal repeat><p className="section-kicker">One connected flow</p><h2 className="mt-4 max-w-[560px] text-[clamp(3.4rem,5.4vw,5.6rem)] leading-[.91]">A better way to move money <span className="script-accent">forward.</span></h2><p className="mt-5 max-w-md text-[14px] leading-relaxed text-foreground/70">Every step is visible. Every message is grounded in your data. Every exception has a next action.</p></Reveal><Reveal repeat delay={.08} className="mt-10 pb-5"><InvoiceScene /></Reveal></div>
      <div className="space-y-4 lg:pt-20">{steps.map(({ number, title, body, icon: Icon }) => <Reveal key={number} repeat><article className="flow-step-card glass-panel group flex min-h-[185px] gap-5 rounded-[1.5rem] p-6 transition-all duration-300 hover:-translate-y-1 hover:border-[#111184]/35 hover:shadow-[0_18px_50px_rgba(17,17,132,.15)] sm:p-8 lg:min-h-[210px]"><span className="text-xs font-semibold text-[#111184]">{number}</span><div><span className="mb-5 grid h-11 w-11 place-items-center rounded-xl bg-[#111184]/10 text-[#111184] transition-transform duration-300 group-hover:rotate-6 group-hover:scale-110"><Icon size={22} /></span><h3 className="text-xl font-semibold sm:text-2xl">{title}</h3><p className="mt-3 max-w-md text-[13px] leading-relaxed text-foreground/65 sm:text-sm">{body}</p></div></article></Reveal>)}</div>
    </div></section>

    <section className="relative overflow-hidden border-b border-foreground/10 py-20 sm:py-28"><div className="pointer-events-none absolute right-0 top-0 h-[500px] w-[500px] bg-[radial-gradient(circle,rgba(17,17,132,.13),transparent_65%)]" /><div className="relative mx-auto max-w-[1260px] px-4 sm:px-7"><Reveal><p className="section-kicker">Your whole receivables picture</p><div className="mt-4 flex flex-col justify-between gap-5 md:flex-row md:items-end"><h2 className="max-w-[730px] text-[clamp(3.3rem,5.4vw,5.5rem)] leading-[.93]">One place for every <span className="script-accent">moving part.</span></h2><Link href="/features" className="inline-flex items-center gap-2 text-sm font-semibold text-[#111184] hover:underline">Explore all features <ArrowUpRight size={17} /></Link></div></Reveal><div className="mt-11 grid gap-4 sm:grid-cols-2">{capabilities.map(({ icon: Icon, title, body, href }, i) => <Reveal key={title} delay={i * .05}><Link href={href} className="group glass-panel block h-full min-h-[235px] rounded-[1.5rem] p-7 transition-transform hover:-translate-y-1 sm:p-8"><div className="flex justify-between"><span className="grid h-13 w-13 place-items-center rounded-2xl bg-gradient-to-br from-[#111184]/20 to-blue-500/20 text-[#111184]"><Icon size={24} /></span><ArrowUpRight size={18} className="text-foreground/35 transition group-hover:text-[#111184]" /></div><h3 className="mt-8 text-xl font-semibold sm:text-2xl">{title}</h3><p className="mt-3 max-w-md text-[13px] leading-relaxed text-foreground/65 sm:text-sm">{body}</p></Link></Reveal>)}</div></div></section>

    <section className="border-b border-foreground/10 py-20 sm:py-28"><div className="mx-auto grid max-w-[1260px] gap-10 px-4 sm:px-7 lg:grid-cols-2 lg:items-center lg:gap-20"><Reveal><AiVisual /></Reveal><Reveal delay={.1}><p className="section-kicker">Intelligence with guardrails</p><h2 className="mt-4 text-[clamp(3.3rem,5vw,5.2rem)] leading-[.92]">AI that knows <span className="script-accent">when to ask.</span></h2><p className="mt-5 text-[14px] leading-relaxed text-foreground/65 sm:text-base">The AI Collector drafts from verified invoice details. Clear business rules decide eligibility and timing. Disputes, payment claims, and uncertain replies move to human review.</p><div className="mt-7 space-y-3">{["No invented fees, threats, or payment claims", "Approval modes and quiet hours you control", "Verified payment stops collection"].map((item) => <p key={item} className="flex gap-3 text-[13px] text-foreground/80 sm:text-sm"><Check size={18} className="shrink-0 text-emerald-400" />{item}</p>)}</div><Link href="/features#user-control" className="mt-8 inline-flex items-center gap-2 text-sm font-semibold text-[#111184] hover:underline">See how control works <ArrowRight size={16} /></Link></Reveal></div></section>

    <section className="border-b border-foreground/10 py-20 sm:py-28"><div className="mx-auto max-w-[980px] px-4 sm:px-7"><Reveal><p className="section-kicker">Good questions</p><h2 className="mt-4 text-[clamp(3.3rem,5vw,5rem)] leading-[.93]">Frequently <span className="script-accent">asked.</span></h2></Reveal><div className="mt-10 space-y-3">{faqs.map((faq, i) => <Reveal key={faq.q} delay={i * .04}><details className="group glass-panel rounded-2xl p-5 sm:p-6"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 text-sm font-semibold marker:content-none sm:text-base">{faq.q}<span className="text-2xl font-light text-[#d93c90] transition group-open:rotate-45">+</span></summary><p className="mt-3 max-w-3xl pr-5 text-[13px] leading-relaxed text-foreground/65 sm:text-sm">{faq.a}</p></details></Reveal>)}</div></div></section>

    <section className="hero-dark relative overflow-hidden bg-[#0a0d1e] py-24 text-white sm:py-32"><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_110%,rgba(17,17,132,.45),transparent_45%),radial-gradient(circle_at_5%_5%,rgba(40,62,154,.3),transparent_35%)]" /><div className="marketing-grid absolute inset-0 opacity-[.09]" /><div className="relative mx-auto max-w-[900px] px-4 text-center sm:px-7"><Reveal><p className="section-kicker">The next chapter in receivables</p><h2 className="mt-4 text-[clamp(3.6rem,7vw,7rem)] leading-[.86]">Make every <span className="script-accent">follow-up</span> count.</h2><p className="mx-auto mt-7 max-w-xl text-[14px] text-white/70 sm:text-base">Start with your invoices, set your rules, and give your team one clear place to work.</p><div className="mt-8 flex flex-wrap justify-center gap-3"><Link href="/signup"><Button size="lg">Get started <ArrowUpRight size={17} /></Button></Link><Link href="/pricing"><Button size="lg" variant="outline" className="border-white/25 text-white hover:bg-white/10">See pricing <ArrowRight size={17} /></Button></Link></div></Reveal></div></section>
  </div>;
}
